### ISSUE TITLE
how to fix this ,, ?

### ISSUE THREAD

**Issue by muafakul** [Elringus/NaninovelInventory#1]
![image](https://user-images.githubusercontent.com/13078369/86062701-7f7bcc80-ba93-11ea-93cb-c8c39d6adda9.png)

**Comment by muafakul** [comment]
after i delet nanonovelinventory ,,another errror appear 


![image](https://user-images.githubusercontent.com/13078369/86062841-c8cc1c00-ba93-11ea-83d8-bc4453a4c2da.png)

**Comment by Elringus** [comment]
We're not providing support via github issues; please see  https://naninovel.com/support/ for the available support options.
